
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sun.util.logging.PlatformLogger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class frame1 extends javax.swing.JFrame {
    
    int jam;
    int menit;
    int detik;
    
    public frame1() {
        initComponents();
        
        setTanggal() ;
        setJam() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pesanan = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        total = new javax.swing.JButton();
        bla = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 27)); // NOI18N
        jLabel1.setText("JaKe's ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 130, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 27)); // NOI18N
        jLabel2.setText("Cafe");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 40, 80, 60);

        jLabel23.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel23.setText("your tummy need ");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 110, 170, 30);

        jLabel24.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel24.setText("delicious foods");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(70, 140, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 180, 190);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel3.setText("Menu");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 10, 70, 30);

        jLabel5.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel5.setText("Makanan");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(70, 40, 70, 20);

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 0, 11)); // NOI18N
        jLabel6.setText("Minuman");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 30, 70, 20);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel7.setText("Rib Eye Steak");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 70, 80, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel8.setText("Rp. 50000");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(130, 70, 70, 30);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel9.setText("Dragon Roll Sushi");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 100, 110, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel10.setText("Rp. 45.000");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(130, 100, 70, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel11.setText("Fussili Carbonara");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 120, 120, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel12.setText("Rp. 45.000");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(130, 120, 80, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel4.setText("Oreo Frappe");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(200, 70, 80, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel13.setText("Green Tea Latte");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(200, 100, 100, 30);

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel14.setText("Blue Ocean");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(200, 120, 90, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel15.setText("Rp. 20.000");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(330, 60, 70, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel16.setText("Rp. 15.000");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(330, 90, 60, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel17.setText("Rp. 20.000");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(330, 120, 60, 30);

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel18.setText("Pecking Duck");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 150, 100, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel19.setText("Rp. 75.000");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(130, 150, 70, 30);

        jLabel20.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel20.setText("Milk Tea");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(200, 150, 80, 30);

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        jLabel21.setText("Rp. 10.000");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(330, 150, 60, 30);

        tanggal.setText("Tanggal");
        jPanel2.add(tanggal);
        tanggal.setBounds(400, 10, 120, 30);

        waktu.setText("Waktu");
        jPanel2.add(waktu);
        waktu.setBounds(400, 40, 120, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(200, 10, 530, 190);

        jPanel3.setBackground(new java.awt.Color(255, 0, 51));
        jPanel3.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Swis721 Hv BT", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Pesanan");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(10, 70, 80, 30);
        jPanel3.add(pesanan);
        pesanan.setBounds(10, 100, 130, 30);
        jPanel3.add(jumlah);
        jumlah.setBounds(10, 160, 80, 30);

        jLabel25.setFont(new java.awt.Font("Swis721 Hv BT", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("No Pembelian");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(10, 0, 120, 30);

        jLabel28.setFont(new java.awt.Font("Swis721 Hv BT", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Jumlah");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(10, 130, 60, 30);
        jPanel3.add(harga);
        harga.setBounds(10, 220, 110, 30);

        jLabel26.setFont(new java.awt.Font("Swis721 Hv BT", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Harga");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(10, 190, 60, 30);
        jPanel3.add(no);
        no.setBounds(10, 40, 130, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 210, 240, 280);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(51, 255, 153));
        jPanel4.setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No Pembelian", "Pesanan", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 450, 150);

        save.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel4.add(save);
        save.setBounds(10, 190, 80, 30);

        clear.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel4.add(clear);
        clear.setBounds(100, 190, 80, 30);

        delete.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel4.add(delete);
        delete.setBounds(190, 190, 80, 30);

        print.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel4.add(print);
        print.setBounds(370, 190, 80, 30);

        refresh.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel4.add(refresh);
        refresh.setBounds(280, 190, 80, 30);

        total.setFont(new java.awt.Font("Segoe UI Symbol", 0, 11)); // NOI18N
        total.setText("Total");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel4.add(total);
        total.setBounds(120, 240, 70, 30);

        bla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blaActionPerformed(evt);
            }
        });
        jPanel4.add(bla);
        bla.setBounds(200, 240, 100, 30);

        jPanel6.add(jPanel4);
        jPanel4.setBounds(260, 210, 470, 280);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 750, 500);

        setBounds(0, 0, 763, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        if ("".equals(no.getText()) || "".equals(pesanan.getText()) || "".equals(jumlah.getText())  || "".equals(harga.getText())) 
        {
           JOptionPane.showMessageDialog(this, "Mohon Lengkapi Pesanan", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int price = Integer.parseInt(String.valueOf(harga.getText()));
            int jum = Integer.parseInt(String.valueOf(jumlah.getText()));
            int ttl = price * jum;
            
            bla.setText(String.valueOf(ttl));
        
        String SQL = "INSERT INTO tb_transaksi(no_pembelian,pesanan,jumlah,harga) VALUES('"+no.getText()+"','"+pesanan.getText()+"','"+jumlah.getText()+"','"+harga.getText()+"');";
        int status = db.execute(SQL);
        if (status == 1) {
            JOptionPane.showMessageDialog(this, "Pesanan berhasil ditambahkan", "Success",JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Pesanan gagal ditambahkan", "Failed", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void blaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blaActionPerformed
        
    }//GEN-LAST:event_blaActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        pesanan.setText("");
        jumlah.setText("");
        harga.setText("");
        bla.setText("");
        no.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        int baris = table.getSelectedRow();
        if (baris != -1) {
            String pesan = table.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE no_pembelian = "+pesan+";";
            
            int status = db.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Pesanan berhasil dihapus", "Success !", JOptionPane.INFORMATION_MESSAGE);
                selectdata();
            } else {
                JOptionPane.showMessageDialog(this, "Pesanan gagal dihapus", "Failed", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang akan dihapus", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        MessageFormat header = new MessageFormat("Pesanan JaKe's Cafe");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");
        
        try {
            table.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        int baris = table.getRowCount();
        int biaya = 0;
        int jml, hrg;
        TableModel tabelModel;
        tabelModel = table.getModel();
        
        for (int i = 0; i < baris; i++) {
            jml = Integer.parseInt(tabelModel.getValueAt(i, 2).toString());
            hrg = Integer.parseInt(tabelModel.getValueAt(i, 3).toString());
            biaya = biaya + (jml * hrg);
        }
        if (biaya > 200000) {
            int discount = biaya * 10 /100;
            bla.setText(String.valueOf(biaya - discount));
        } else
            bla.setText(String.valueOf(biaya));
    }//GEN-LAST:event_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bla;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField no;
    private javax.swing.JTextField pesanan;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable table;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton total;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"no_pembelian","pesanan","jumlah","harga"};
        DefaultTableModel dtm  = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_transaksi";
        ResultSet rs = db.executeQuery(SQL);
        
        try {
            while (rs.next()) {
                String no_pembelian = rs.getString(1);
                String pesanan= rs.getString(2);
                String jumlah = rs.getString(3);
                String harga = rs.getString(4);
                String data[] = {no_pembelian,pesanan,jumlah,harga,};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        table.setModel(dtm);
    }

    private void selectdata() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setTanggal() {
        java.util.Date skrg = new java.util.Date() ;
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy") ;
        tanggal.setText(kal.format(skrg));
    }

    private void setJam() {
            ActionListener taskPerformer = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
            
                Date dt = new Date() ;
                int nilai_jam = dt.getHours() ;
                int nilai_menit = dt.getMinutes() ;
                int nilai_detik = dt.getSeconds() ;
                if(nilai_jam <= 9){
                    
                 jam = 0 ;   
                    
                } if(nilai_menit <= 9){
                    
                 menit = 0 ;   
                    
                } if(nilai_jam <= 9){
                    
                 detik = 0 ;   
                    
                }
                String Jam = jam + Integer.toString(nilai_jam) ;
                String Menit = menit + Integer.toString(nilai_menit) ;
                String Detik = detik + Integer.toString(nilai_detik) ;
                
                waktu.setText("Jam " + Jam + ":" + Menit + ":" + Detik );
            }
            
        };
        
            new Timer(100, taskPerformer).start() ;
    }
    }